# Copyright © 2022 by Jan Dockx
#
# Licensed under the Apache License, Version 2.0 (the “License”);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an “AS IS” BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

image: node:16

definitions:
  steps:
    - step: &test
        name: Latest Node N
        image: IMAGE
        caches:
          - npm16
        script:
          - git submodule update --init
          - scripts/common/npm/testCi.sh
  caches:
    npm16: ~/.npm
    npm18: ~/.npm
  branches:
    - branch: &fullTestAndTag
        - parallel:
            - step:
                <<: *test
                name: Latest Node 16
                image: node:16
                caches:
                  - npm16
            - step:
                <<: *test
                name: Latest Node 18
                image: node:18
                caches:
                  - npm18
        - step:
            name: Tag & Push to Github
            caches:
              - node
            script:
              - git submodule update --init
              - scripts/common/git/tagBitbucket.sh
              - scripts/common/git/pushToRemote.sh https://${GITHUB_CREDENTIALS}@github.com/Toryt/allen.git
pipelines:
  branches:
    master: *fullTestAndTag
    bugfix/**: *fullTestAndTag
    feature/**: *fullTestAndTag
    hotfix/**: *fullTestAndTag
    release/**: *fullTestAndTag
  tags:
    v*: *fullTestAndTag
